version: "3.9"

services:
  backend:
    build:
      context: .
    volumes:
      - .:/code
    ports:
      - 8001:8001
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5433:5432

  
volumes:
  postgres_data:


