# Generated by Django 5.0.4 on 2024-05-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_password2_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
    ]
